export default {
  MARKET: {
    FETCH_MARKET: "FETCH_MARKET",
    FETCH_MARKET_FUlLFILLED: "FETCH_MARKET_FUlLFILLED",
    FETCH_SYMBOL: "FETCH_SYMBOL",
    FETCH_SYMBOL_FUlLFILLED: "FETCH_SYMBOL_FUlLFILLED",
  },
  SEARCH: {
    APPLY_SEARCH_QUERY: "APPLY_SEARCH_QUERY",
  },
};
